// ABOUTME: Pre-build script that reads template and reference files from disk.
// ABOUTME: Generates src/embedded-assets.ts with string constants for the MCP server.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const templateFiles = [
  { key: "architecture", file: "architecture.html" },
  { key: "dataTable", file: "data-table.html" },
  { key: "mermaidFlowchart", file: "mermaid-flowchart.html" },
  { key: "slideDeck", file: "slide-deck.html" },
] as const;

const referenceFiles = [
  { key: "cssPatterns", file: "css-patterns.md" },
  { key: "libraries", file: "libraries.md" },
  { key: "responsiveNav", file: "responsive-nav.md" },
  { key: "slidePatterns", file: "slide-patterns.md" },
] as const;

function escapeForTemplateLiteral(content: string): string {
  return content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

function readAndEscape(dir: string, filename: string): string {
  const filePath = join(projectRoot, dir, filename);
  const raw = readFileSync(filePath, "utf-8");
  return escapeForTemplateLiteral(raw);
}

function buildEntries(
  dir: string,
  files: ReadonlyArray<{ key: string; file: string }>,
): string {
  return files
    .map(({ key, file }) => {
      const escaped = readAndEscape(dir, file);
      return `  ${key}: \`${escaped}\`,`;
    })
    .join("\n");
}

try {
  const templateEntries = buildEntries("templates", templateFiles);
  const referenceEntries = buildEntries("references", referenceFiles);

  const output = `// ABOUTME: Auto-generated module containing embedded template and reference content.
// ABOUTME: Generated by scripts/embed-assets.ts — do not edit manually.

export const templates = {
${templateEntries}
} as const;

export const references = {
${referenceEntries}
} as const;
`;

  const outPath = join(projectRoot, "src", "embedded-assets.ts");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, output, "utf-8");

  process.stderr.write(`Embedded assets written to ${outPath}\n`);
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`Error: ${message}\n`);
  process.exit(1);
}
