import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { GoogleGenAI } from "@google/genai";
import * as fs from "fs/promises";
import * as path from "path";
import * as os from "os";

const server = new Server(
  {
    name: "visual-explainer-mcp",
    version: "0.5.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

const apiKey = process.env.NANOBANANA_GEMINI_API_KEY || process.env.GEMINI_API_KEY;

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "generate_image",
        description: "Generate an image using the Gemini API. Useful for hero banners, illustrations, or any visual asset requested by the user.",
        inputSchema: {
          type: "object",
          properties: {
            prompt: { type: "string", description: "The image prompt" },
            aspectRatio: { type: "string", description: "Aspect ratio (e.g. '16:9', '1:1', '3:4', '4:3'). Default is '1:1'." },
            count: { type: "number", description: "Number of images to generate. Default is 1." }
          },
          required: ["prompt"]
        }
      },
      {
        name: "generate_icon",
        description: "Generate an app icon or UI element",
        inputSchema: {
          type: "object",
          properties: {
            prompt: { type: "string", description: "The icon prompt" }
          },
          required: ["prompt"]
        }
      },
      {
        name: "generate_pattern",
        description: "Generate a seamless pattern or texture",
        inputSchema: {
          type: "object",
          properties: {
            prompt: { type: "string", description: "The pattern prompt" }
          },
          required: ["prompt"]
        }
      }
    ]
  };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  
  if (!apiKey) {
    return {
      content: [{ type: "text", text: "Error: GEMINI_API_KEY environment variable is missing." }],
      isError: true
    };
  }

  const ai = new GoogleGenAI({ apiKey });
  const modelName = process.env.NANOBANANA_MODEL || 'gemini-3.1-flash-image-preview';

  try {
    if (name === "generate_image" || name === "generate_icon" || name === "generate_pattern") {
      const prompt = String(args?.prompt || "");
      const count = Number(args?.count || 1);
      const aspectRatioStr = String(args?.aspectRatio || "1:1");
      
      const response = await ai.models.generateImages({
        model: modelName,
        prompt: prompt,
        config: {
          numberOfImages: count,
          aspectRatio: aspectRatioStr,
          outputMimeType: "image/jpeg"
        }
      });
      
      const results = [];
      const tmpDir = path.join(os.tmpdir(), "visual-explainer");
      await fs.mkdir(tmpDir, { recursive: true });
      
      if (!response.generatedImages || response.generatedImages.length === 0) {
        return {
          content: [{ type: "text", text: "No images were generated by the API." }],
          isError: true
        };
      }

      for (let i = 0; i < response.generatedImages.length; i++) {
        const imgBytes = response.generatedImages[i].image?.imageBytes;
        if (!imgBytes) continue;
        
        const buffer = Buffer.from(imgBytes, "base64");
        const filePath = path.join(tmpDir, `img_${Date.now()}_${i}.jpg`);
        await fs.writeFile(filePath, buffer);
        results.push({
          type: "text",
          text: `Image generated and saved to ${filePath}. Base64 data URI (if you need to embed it in HTML): data:image/jpeg;base64,${imgBytes}`
        });
      }
      
      return { content: results };
    }
    
    return {
      content: [{ type: "text", text: `Unknown tool: ${name}` }],
      isError: true
    };
  } catch (error: any) {
    return {
      content: [{ type: "text", text: `Error generating image: ${error.message}` }],
      isError: true
    };
  }
});

async function run() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("Visual Explainer MCP Server running on stdio");
}

run().catch((error) => {
  console.error("Server error:", error);
  process.exit(1);
});