// ABOUTME: Registers image generation tools (generate_image, generate_icon, generate_pattern)
// ABOUTME: with the MCP server using Zod schemas, structured output, and logging.

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { GoogleGenAI } from "@google/genai";
import * as fs from "fs/promises";
import * as path from "path";
import * as os from "os";

const ASPECT_RATIOS = ["1:1", "16:9", "9:16", "3:4", "4:3"] as const;
const ICON_STYLES = ["flat", "outlined", "filled"] as const;

const imageResultSchema = z.object({
  filePaths: z.array(z.string()),
  count: z.number(),
});

const toolAnnotations = {
  readOnlyHint: false,
  destructiveHint: false,
  idempotentHint: false,
  openWorldHint: true,
} as const;

async function log(
  server: McpServer,
  level: "info" | "error" | "warning",
  message: string,
) {
  try {
    await server.server.sendLoggingMessage({ level, data: message });
  } catch {
    // Logging failures should not break tool execution
  }
}

async function generateWithGemini(
  server: McpServer,
  prompt: string,
  options: { aspectRatio: string; count: number },
) {
  const apiKey =
    process.env.NANOBANANA_GEMINI_API_KEY || process.env.GEMINI_API_KEY;

  if (!apiKey) {
    return {
      content: [
        {
          type: "text" as const,
          text: "Error: GEMINI_API_KEY environment variable is missing.",
        },
      ],
      isError: true,
    };
  }

  await log(
    server,
    "info",
    `Generating ${options.count} image(s): "${prompt.slice(0, 80)}"`,
  );

  const ai = new GoogleGenAI({ apiKey });
  const modelName = process.env.NANOBANANA_MODEL || "gemini-3.1-flash-image-preview";

  try {
    const response = await ai.models.generateImages({
      model: modelName,
      prompt,
      config: {
        numberOfImages: options.count,
        aspectRatio: options.aspectRatio,
        outputMimeType: "image/jpeg",
      },
    });

    if (!response.generatedImages || response.generatedImages.length === 0) {
      return {
        content: [
          {
            type: "text" as const,
            text: "No images were generated by the API.",
          },
        ],
        isError: true,
      };
    }

    const tmpDir = path.join(os.tmpdir(), "visual-explainer");
    await fs.mkdir(tmpDir, { recursive: true });

    const filePaths: string[] = [];
    const results: Array<{ type: "text"; text: string }> = [];

    for (let i = 0; i < response.generatedImages.length; i++) {
      const imgBytes = response.generatedImages[i].image?.imageBytes;
      if (!imgBytes) continue;

      const buffer = Buffer.from(imgBytes, "base64");
      const filePath = path.join(tmpDir, `img_${Date.now()}_${i}.jpg`);
      await fs.writeFile(filePath, buffer);
      filePaths.push(filePath);

      results.push({
        type: "text",
        text: `Image saved to ${filePath}. Data URI: data:image/jpeg;base64,${imgBytes}`,
      });
    }

    await log(server, "info", `Generated ${filePaths.length} image(s)`);

    return {
      content: results,
      structuredContent: { filePaths, count: filePaths.length },
    };
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    await log(server, "error", `Image generation failed: ${message}`);
    return {
      content: [
        {
          type: "text" as const,
          text: `Error generating image: ${message}`,
        },
      ],
      isError: true,
    };
  }
}

export function registerTools(server: McpServer): void {
  server.registerTool(
    "generate_image",
    {
      title: "Generate Image",
      description:
        "Generate images using the Gemini API. Creates hero banners, illustrations, or any visual asset.",
      inputSchema: {
        prompt: z.string().describe("The image generation prompt"),
        aspectRatio: z
          .enum(ASPECT_RATIOS)
          .default("1:1")
          .describe("Image aspect ratio"),
        count: z
          .number()
          .min(1)
          .max(4)
          .default(1)
          .describe("Number of images to generate (1-4)"),
      },
      outputSchema: imageResultSchema,
      annotations: toolAnnotations,
    },
    async ({ prompt, aspectRatio, count }) => {
      return generateWithGemini(server, prompt, {
        aspectRatio: aspectRatio ?? "1:1",
        count: count ?? 1,
      });
    },
  );

  server.registerTool(
    "generate_icon",
    {
      title: "Generate Icon",
      description:
        "Generate an app icon or UI element with a specified visual style.",
      inputSchema: {
        prompt: z.string().describe("What the icon should depict"),
        style: z
          .enum(ICON_STYLES)
          .default("flat")
          .describe("Icon visual style"),
      },
      outputSchema: imageResultSchema,
      annotations: toolAnnotations,
    },
    async ({ prompt, style }) => {
      const fullPrompt = `${style ?? "flat"} style icon on transparent background: ${prompt}`;
      return generateWithGemini(server, fullPrompt, {
        aspectRatio: "1:1",
        count: 1,
      });
    },
  );

  server.registerTool(
    "generate_pattern",
    {
      title: "Generate Pattern",
      description:
        "Generate a seamless, tileable pattern or texture for backgrounds.",
      inputSchema: {
        prompt: z.string().describe("What kind of pattern to generate"),
      },
      outputSchema: imageResultSchema,
      annotations: toolAnnotations,
    },
    async ({ prompt }) => {
      const fullPrompt = `Seamless tileable pattern: ${prompt}`;
      return generateWithGemini(server, fullPrompt, {
        aspectRatio: "1:1",
        count: 1,
      });
    },
  );
}
